### ISSUE TITLE
Why we storing services in property?

### ISSUE THREAD

**Issue by vforv** [nehalist/di-ts#1]
Hello I saw this looks pretty good.

But I have not understand why we using service property when we don't using it when resolving dependencies?

Here:
https://github.com/nehalist/di-ts/blob/044bc902f62a82ad3e4f96e277f01b4f56b10e07/src/Injector.ts#L12

Also how is it possible to mock some dependencies?

Thanks

**Comment by nehalist** [comment]
Good point. It's actually a copy/paste mistake from my very own injector, which is able to store resolved instances and return them in case the services are _shared_. But, nevertheless, you're completely right about storing services in this case is completely useless.

Will update the article asap, thank you.

**Comment by vforv** [comment]
Aha, okay. Anyway article helped me create small DI framework, thanks!

**Comment by kpfromer** [comment]
@nehalist is it possible that you could link your more advanced injector? It would be cool to see how it works.

**Comment by nehalist** [comment]
@kpfromer you could take a look at https://github.com/inversify/InversifyJS. Otherwise just search for "github ts di" to find some more advanced DI systems.
